# Generated by Django 2.2.1 on 2019-05-23 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=32)),
                ('age', models.IntegerField()),
                ('idcard', models.IntegerField(unique=True)),
                ('attr', models.CharField(max_length=1024)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('detail', models.TextField()),
            ],
            options={
                'verbose_name': '医疗记录',
                'verbose_name_plural': '医疗记录',
                'ordering': ['rid'],
            },
        ),
    ]
