# Generated by Django 2.2.1 on 2019-05-25 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190523_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='key',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
